### ISSUE TITLE
SGA-ICE install

### ISSUE THREAD

**Issue by jayramr** [hillerlab/IterativeErrorCorrection#7]
Hi, 

I tried to install sga-ice, but when i try to excecute , getting below error

```
./SGA-ICE.py -h
File "/data/install/sga-ice/IterativeErrorCorrection-1.0/./SGA-ICE.py", line 35
    print '### Input directory is:', args.inputDir
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

Please advice 

Thanks
Jay

**Comment by MichaelHiller** [comment]
Pls try now. I set /usr/bin/env python2.7
These print errors are differences between python 2 and 3

**Comment by jayramr** [comment]
Thanks i tested this worked.

Could you please release the latest release with this change?

**Comment by MichaelHiller** [comment]
Done.

**Comment by jayramr** [comment]
THanks i will make the bioconda package for this. I'm closing this one
